### PR TITLE
Closed prs and issues count

### PR DESCRIPTION
**Pull request by k0nserv**
Sister PR https://github.com/CocoaPods/Humus/pull/8

/c @floere, @orta

### CODE REVIEW

**Comment by segiddins** [comment]
looks good to me!

**Comment by orta** [comment]
looks good here

**Comment by floere** [comment]
Good catch!

**Comment by orta** [comment]
OK, I've migrated humus. I've pushed the new metrics to heroku.

**Comment by orta** [comment]
They're showing in the API, http://metrics.cocoapods.org/api/v1/pods/URITemplate

obviously without data for now

**Comment by orta** [comment]
Good show @k0nserv

**Comment by k0nserv** [comment]
:+1: great stuff

**Pull request merged**
